export default {
  testEnvironment: 'node',
  transform: {},
  moduleFileExtensions: ['js', 'mjs', 'json'],
  testMatch: ['**/*.test.js', '**/*.spec.js'],
  verbose: true,
  setupFilesAfterEnv: ['<rootDir>/jest.setup.js'],
  collectCoverage: true,
  coverageDirectory: 'coverage',
  coverageReporters: ['lcov', 'text', 'text-summary'],
  collectCoverageFrom: [
    'src/**/*.js',
    '!src/**/__tests__/**',
    '!src/**/index.js',
    '!src/test*.js',  
    '!src/scripts/**',
    '!src/server.js',
    '!src/config/redis.js',
    '!src/sockets/syncGateway.js',
    '!src/utils/requestLogger.js',
    '!src/utils/metrics.js',
    '!src/utils/rateLimiter.js',
    '!src/utils/retryWithBackoff.js',
    '!src/utils/streamUrlCache.js', 
  ],
  coveragePathIgnorePatterns: ['/node_modules/'],
  testTimeout: 10000,
};